version: '2'
services:
  morse_code:
    build: ./morse_code
    volumes:
      - shared_folder:/usr/src/app/public
    environment:
      - MORSE_CODE_TONE_FREQ=400
      - MORSE_CODE_SPEED=20
  fm_radio:
    build: ./fm_radio
    privileged: true
    # depends_on:
    #   - shared_folder
    restart: "no"
    volumes:
      - shared_folder:/app/PiFmAdv/src/public
    # command:  cwwav -f 700 -w 20 -o hello_world.wav /app/PiFmAdv/src/morse_data.txt
    # command:  /bin/sh -c "cwwav -f 400 -w 20 -o /app/hello_world.wav /app/morse_data.txt &&   ./pi_fm_adv --freq 90.7  --audio /app/hello_world.wav"
    # command: /bin/sh -c " find . -name 'morse_data.txt' |  entr -r cwwav -f 400 -w 20 -o /app/PiFmAdv/src/public/hello_world.wav /app/PiFmAdv/src/public/morse_data.txt &  sudo /app/PiFmAdv/src/pi_fm_adv --freq 90.5 --mpx 30 --wait 0 --audio /app/PiFmAdv/src/public/hello_world.wav"
    # command: /bin/sh -c "exec /app/start.sh"

    # command: /bin/sh -c " find . -name 'morse_data.txt' |  entr -r cwwav -f 400 -w 20 -o /app/PiFmAdv/src/public/hello_world.wav /app/PiFmAdv/src/public/morse_data.txt &  sudo /app/PiFmAdv/src/pi_fm_adv --freq $RADIO_STATION_FREQ --audio /app/PiFmAdv/src/public/hello_world.wav"

    # ${RADIO_STATION_FREQ:=90.5} -> [Assigning default values to shell variables with a single command in bash - Stack Overflow](https://stackoverflow.com/questions/2013547/assigning-default-values-to-shell-variables-with-a-single-command-in-bash)
    # command: /bin/sh -c " find . -name 'morse_data.txt' |  entr -r cwwav -f 400 -w 20 -o /app/PiFmAdv/src/public/hello_world.wav /app/PiFmAdv/src/public/morse_data.txt &  sudo /app/PiFmAdv/src/pi_fm_adv --freq ${RADIO_STATION_FREQ:=90.5} --audio /app/PiFmAdv/src/public/hello_world.wav"
    # command: ping -c 10000 www.google.com
    environment:
      - RADIO_STATION_FREQ=90.7
      - GPIO_PIN=4
      # - ANTENNA_PIN: 4
  api:
    build: ./api
    ports:
      - "80:80"
    volumes:
      - shared_folder:/app/src/public
    environment:
      - API_PORT=80
# used for sharing a filepipe to send audio data between the api server and the fm radio code: "pirateradio"
# for more info see this stackoverflow post
# https://stackoverflow.com/questions/44284484/docker-compose-share-named-volume-between-multiple-containers
volumes:
  shared_folder: