version: '2'
services:
  pirateradio:
    build: ./pirateradio
    privileged: true
    # depends_on:
    #   - shared_pipe
    restart: "no"
    volumes:
      - shared_pipe:/usr/src/app/PiFmAdv/src/public
    # command:  cwwav -f 700 -w 20 -o hello_world.wav /usr/src/app/PiFmAdv/src/morse_data.txt
    # command:  /bin/sh -c "cwwav -f 400 -w 20 -o /usr/src/app/hello_world.wav /usr/src/app/morse_data.txt &&   ./pi_fm_adv --freq 90.7  --audio /usr/src/app/hello_world.wav"
    command: /bin/sh -c " find . -name 'morse_data.txt' |  entr -r cwwav -f 400 -w 20 -o /usr/src/app/PiFmAdv/src/public/hello_world.wav /usr/src/app/PiFmAdv/src/public/morse_data.txt &   /usr/src/app/PiFmAdv/src/pi_fm_adv --freq 90.7  --audio /usr/src/app/PiFmAdv/src/public/hello_world.wav"
    # command: ping -c 10000 www.google.com

  api:
    build: ./api
    ports:
      - "80:80"
    volumes:
      - shared_pipe:/usr/src/app/public
# used for sharing a filepipe to send audio data between the api server and the fm radio code: "pirateradio"
# for more info see this stackoverflow post
# https://stackoverflow.com/questions/44284484/docker-compose-share-named-volume-between-multiple-containers
volumes:
  shared_pipe: