 
FROM wisehackermonkey/netpirate_base:latest

WORKDIR /app

RUN git clone https://github.com/markondej/fm_transmitter
WORKDIR /app/fm_transmitter
RUN make

WORKDIR /app
COPY . ./
WORKDIR /public

RUN ["chmod", "+x", "/app/start.sh"]
CMD ["/bin/bash","/app/start.sh"]